export const initialHelps = [
  {
    id: 0,
    text:
      'OLÁ! SEJA BEM VINDA! SEJA BEM VINDO! ESTE É O <br/><br/> NESTA ATIVIDADE, VOCÊ DEVERÁ MEDIR ALGUNS OBJETOS UTILIZANDO A NOSSA RÉGUA VIRTUAL. <br/><br/>VEJA COMO É QUE SE FAZ...',
    class: 'help-0'
  },
  {
    id: 1,
    text:
      'O OBJETO QUE VOCÊ PRECISA MEDIR VAI ESTAR NA TELA. PARA FAZER A MEDIÇÃO, SELECIONE A RÉGUA E ARRASTE-A PRÓXIMO AO OBJETO.',
    class: 'help-1'
  },
  {
    id: 2,
    text:
      'ALGUMAS VEZES SERÁ PRECISO GIRAR A RÉGUA PARA MEDIR O LADO CERTO DO OBJETO. PARA ISSO É SÓ CLICAR NO BOTÃO DE GIRAR NO CENTRO DELA. ESTÁ EM DÚVIDA DE QUAL LADO MEDIR? COLOQUE A SETINHA DO MOUSE SOBRE O QUE É PEDIDO NO ENUNCIADO!',
    class: 'help-2'
  },
  {
    id: 3,
    text:
      'QUANDO FINALIZAR A MEDIÇÃO, CLIQUE NA CAIXA DE TEXTO ABAIXO E DIGITE A MEDIDA ENCONTRADA. CLIQUE EM CONFIRMAR. SE ESTIVER CORRETO, VOCÊ AVANÇA. SE NÃO, SEM PROBLEMAS, VOCÊ PODE TENTAR DE NOVO!',
    class: 'help-3'
  }
]

export const helps = [
  {
    id: 1,
    text:
      'O OBJETO QUE VOCÊ PRECISA MEDIR VAI ESTAR NA TELA. PARA FAZER A MEDIÇÃO, SELECIONE A RÉGUA E ARRASTE-A PRÓXIMO AO OBJETO.',
    class: 'help-1'
  },
  {
    id: 2,
    text:
      'ALGUMAS VEZES SERÁ PRECISO GIRAR A RÉGUA PARA MEDIR O LADO CERTO DO OBJETO. PARA ISSO É SÓ CLICAR NO BOTÃO DE GIRAR NO CENTRO DELA. ESTÁ EM DÚVIDA DE QUAL LADO MEDIR? COLOQUE A SETINHA DO MOUSE SOBRE O QUE É PEDIDO NO ENUNCIADO!',
    class: 'help-2'
  },
  {
    id: 3,
    text:
      'QUANDO FINALIZAR A MEDIÇÃO, CLIQUE NA CAIXA DE TEXTO ABAIXO E DIGITE A MEDIDA ENCONTRADA. CLIQUE EM CONFIRMAR. SE ESTIVER CORRETO, VOCÊ AVANÇA. SE NÃO, SEM PROBLEMAS, VOCÊ PODE TENTAR DE NOVO!',
    class: 'help-3'
  }
]
