export const listObj = [
  {
    id: 0,
    nome: 'cola',
    bg: 'bg-cola',
    nomeEx: 'tubo de cola',
    imageG: 'gcola',
    imageP: 'pcola',
    isSelected: true,
    isCompleted: false,
    regua: 'regua015',
    resposta: 7,
    artigo: 'do',
    medida: 'altura',
    medidaArtigo: 'a'
  },
  {
    id: 1,
    nome: 'estojo',
    bg: 'bg-estojo',
    nomeEx: 'estojo',
    imageG: 'gestojo',
    imageP: 'pestojo',
    isSelected: false,
    isCompleted: false,
    regua: 'regua030',
    resposta: 15,
    artigo: 'do',
    medida: 'comprimento',
    medidaArtigo: 'o'
  },
  {
    id: 2,
    nome: 'caneta',
    bg: 'bg-caneta',
    nomeEx: 'caneta',
    imageG: 'gcaneta',
    imageP: 'pcaneta',
    isSelected: false,
    isCompleted: false,
    regua: 'regua425caneta',
    resposta: 14,
    artigo: 'da',
    medida: 'comprimento',
    medidaArtigo: 'o'
  },
  {
    id: 3,
    nome: 'boneco',
    bg: 'bg-boneco',
    nomeEx: 'boneco',
    imageG: 'gboneco',
    imageP: 'pboneco',
    isSelected: false,
    isCompleted: false,
    regua: 'regua1328boneco',
    resposta: 14,
    artigo: 'do',
    medida: 'altura',
    medidaArtigo: 'a'
  },
  {
    id: 4,
    nome: 'livro',
    bg: 'bg-livro',
    nomeEx: 'livro',
    imageG: 'glivro',
    imageP: 'plivro',
    isSelected: false,
    isCompleted: false,
    regua: 'regua830livro',
    resposta: 14,
    artigo: 'do',
    medida: 'largura',
    medidaArtigo: 'a'
  }
]
