export const listObj = [
  {
    id: 0,
    nome: 'cola',
    bg: 'bg-cola',
    nomeEx: 'tubo de cola',
    imageG: 'gcola',
    imageP: 'pcola',
    isSelected: true,
    isCompleted: false,
    regua: 'regua015',
    resposta: 7,
    artigo: 'do',
    medida: 'altura',
    medidaArtigo: 'a',
    textCorrect: 'VOCÊ MEDIU CORRETAMENTE A ALTURA DO TUBO DE COLA! PARABÉNS!',
    popupCorrect: 'popup-isso',
    indicativo: 'medidorcola'
  },
  {
    id: 1,
    nome: 'estojo',
    bg: 'bg-estojo',
    nomeEx: 'estojo',
    imageG: 'gestojo',
    imageP: 'pestojo',
    isSelected: false,
    isCompleted: false,
    regua: 'regua030',
    resposta: 15,
    artigo: 'do',
    medida: 'comprimento',
    medidaArtigo: 'o',
    textCorrect: 'VOCÊ MEDIU CORRETAMENTE O COMPRIMENTO DO ESTOJO! MUITO BEM!',
    popupCorrect: 'popup-correto',
    indicativo: 'medidorestojo'
  },
  {
    id: 2,
    nome: 'caneta',
    bg: 'bg-caneta',
    nomeEx: 'caneta',
    imageG: 'gcaneta',
    imageP: 'pcaneta',
    isSelected: false,
    isCompleted: false,
    regua: 'regua425caneta',
    resposta: 14,
    artigo: 'da',
    medida: 'comprimento',
    medidaArtigo: 'o',
    textCorrect: 'VOCÊ MEDIU CORRETAMENTE O COMPRIMENTO DA CANETA! ARRASOU!',
    popupCorrect: 'popup-boa',
    indicativo: 'medidorcaneta'
  },
  {
    id: 3,
    nome: 'boneco',
    bg: 'bg-boneco',
    nomeEx: 'boneco',
    imageG: 'gboneco',
    imageP: 'pboneco',
    isSelected: false,
    isCompleted: false,
    regua: 'regua1328boneco',
    resposta: 7,
    artigo: 'do',
    medida: 'altura',
    medidaArtigo: 'a',
    textCorrect: 'VOCÊ MEDIU CORRETAMENTE A ALTURA DO BONECO! MUITO BOM!',
    popupCorrect: 'popup-isso',
    indicativo: 'medidorboneco'
  },
  {
    id: 4,
    nome: 'livro',
    bg: 'bg-livro',
    nomeEx: 'livro',
    imageG: 'glivro',
    imageP: 'plivro',
    isSelected: false,
    isCompleted: false,
    regua: 'regua830livro',
    resposta: 16,
    artigo: 'do',
    medida: 'largura',
    medidaArtigo: 'a',
    textCorrect: 'VOCÊ MEDIU CORRETAMENTE A LARGURA DO LIVRO! PARABÉNS!',
    popupCorrect: 'popup-isso',
    indicativo: 'medidorlivro'
  }
]
